version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    command: mosquitto -c mosquitto-no-auth.conf
    restart: unless-stopped

  postgre-db:
    image: postgres:latest
    container_name: postgre-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33071:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mqtt-publisher:
    build:
      context: ./mqtt-publisher
      dockerfile: Dockerfile
    container_name: mqtt-publisher
    volumes:
      - ./mqtt-publisher:/app
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
    depends_on:
      - mqtt-broker
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      DB_HOST: postgre-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mqtt-broker
      - postgre-db
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "4100:4100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data: